version: '3.9'

services:
  cart-api:
    ports:
      - "6000-8000"
    volumes:
      - .:var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    build:
      context: ./docker
      dockerfile: Dockerfile.local
    restart: always
